export const bible = [
  {
    title: "Genesis",
    content: [
      {
        chapter: "1",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
        ],
      },
      {
        chapter: "2",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
        ],
      },
      {
        chapter: "3",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      {
        chapter: "4",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
        ],
      },
      {
        chapter: "5",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
        ],
      },
      {
        chapter: "6",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
        ],
      },
      {
        chapter: "7",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      {
        chapter: "8",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
        ],
      },
      {
        chapter: "9",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
        ],
      },
      {
        chapter: "10",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
        ],
      },
      {
        chapter: "11",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
        ],
      },
      {
        chapter: "12",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
        ],
      },
      {
        chapter: "13",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
        ],
      },
      {
        chapter: "14",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      {
        chapter: "15",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
        ],
      },
      {
        chapter: "16",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
        ],
      },
      {
        chapter: "17",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
        ],
      },
      {
        chapter: "18",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
        ],
      },
      {
        chapter: "19",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
        ],
      },
      {
        chapter: "20",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
        ],
      },
      {
        chapter: "21",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
        ],
      },
      {
        chapter: "22",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
        ],
      },
      {
        chapter: "23",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
        ],
      },
      {
        chapter: "24",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
          "58",
          "59",
          "60",
          "61",
          "62",
          "63",
          "64",
          "65",
          "66",
          "67",
        ],
      },
      {
        chapter: "25",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
        ],
      },
      {
        chapter: "26",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
        ],
      },
      {
        chapter: "27",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
        ],
      },
      {
        chapter: "28",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
        ],
      },
      {
        chapter: "29",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
        ],
      },
      {
        chapter: "30",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
        ],
      },
      {
        chapter: "31",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
        ],
      },
      {
        chapter: "32",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
        ],
      },
      {
        chapter: "33",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
        ],
      },
      {
        chapter: "34",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
        ],
      },
      {
        chapter: "35",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
        ],
      },
      {
        chapter: "36",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
        ],
      },
      {
        chapter: "37",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
        ],
      },
      {
        chapter: "38",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
        ],
      },
      {
        chapter: "39",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
        ],
      },
      {
        chapter: "40",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
        ],
      },
      {
        chapter: "41",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
          "39",
          "40",
          "41",
          "42",
          "43",
          "44",
          "45",
          "46",
          "47",
          "48",
          "49",
          "50",
          "51",
          "52",
          "53",
          "54",
          "55",
          "56",
          "57",
        ],
      },
      {
        chapter: "42",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
          "35",
          "36",
          "37",
          "38",
        ],
      },
      {
        chapter: "43",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
        ],
      },
      {
        chapter: "44",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
        ],
      },
      {
        chapter: "45",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
        ],
      },
      {
        chapter: "46",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
          "34",
        ],
      },
      {
        chapter: "47",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
        ],
      },
      {
        chapter: "48",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
        ],
      },
      {
        chapter: "49",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30",
          "31",
          "32",
          "33",
        ],
      },
      {
        chapter: "50",
        verses: [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
        ],
      },
    ],
  },
  {
    title: "Exodus",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
    ],
  },
  {
    title: "Leviticus",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
    ],
  },
  {
    title: "Numbers",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
    ],
  },
  {
    title: "Deuteronomy",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
    ],
  },
  {
    title: "Joshua",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
    ],
  },
  {
    title: "Judges",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
    ],
  },
  {
    title: "Ruth",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
    ],
  },
  {
    title: "1 Samuel",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
    ],
  },
  {
    title: "2 Samuel",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
    ],
  },
  {
    title: "1 Kings",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
    ],
  },
  {
    title: "2 Kings",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
    ],
  },
  {
    title: "1 Chronicles",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
    ],
  },
  {
    title: "2 Chronicles",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
    ],
  },
  {
    title: "Ezra",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
    ],
  },
  {
    title: "Nehemiah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
    ],
  },
  {
    title: "Esther",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
    ],
  },
  {
    title: "Job",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
      { chapter: "41", verses: [] },
      { chapter: "42", verses: [] },
    ],
  },
  {
    title: "Psalm",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
      { chapter: "41", verses: [] },
      { chapter: "42", verses: [] },
      { chapter: "43", verses: [] },
      { chapter: "44", verses: [] },
      { chapter: "45", verses: [] },
      { chapter: "46", verses: [] },
      { chapter: "47", verses: [] },
      { chapter: "48", verses: [] },
      { chapter: "49", verses: [] },
      { chapter: "50", verses: [] },
      { chapter: "51", verses: [] },
      { chapter: "52", verses: [] },
      { chapter: "53", verses: [] },
      { chapter: "54", verses: [] },
      { chapter: "55", verses: [] },
      { chapter: "56", verses: [] },
      { chapter: "57", verses: [] },
      { chapter: "58", verses: [] },
      { chapter: "59", verses: [] },
      { chapter: "60", verses: [] },
      { chapter: "61", verses: [] },
      { chapter: "62", verses: [] },
      { chapter: "63", verses: [] },
      { chapter: "64", verses: [] },
      { chapter: "65", verses: [] },
      { chapter: "66", verses: [] },
      { chapter: "67", verses: [] },
      { chapter: "68", verses: [] },
      { chapter: "69", verses: [] },
      { chapter: "70", verses: [] },
      { chapter: "71", verses: [] },
      { chapter: "72", verses: [] },
      { chapter: "73", verses: [] },
      { chapter: "74", verses: [] },
      { chapter: "75", verses: [] },
      { chapter: "76", verses: [] },
      { chapter: "77", verses: [] },
      { chapter: "78", verses: [] },
      { chapter: "79", verses: [] },
      { chapter: "80", verses: [] },
      { chapter: "81", verses: [] },
      { chapter: "82", verses: [] },
      { chapter: "83", verses: [] },
      { chapter: "84", verses: [] },
      { chapter: "85", verses: [] },
      { chapter: "86", verses: [] },
      { chapter: "87", verses: [] },
      { chapter: "88", verses: [] },
      { chapter: "89", verses: [] },
      { chapter: "90", verses: [] },
      { chapter: "91", verses: [] },
      { chapter: "92", verses: [] },
      { chapter: "93", verses: [] },
      { chapter: "94", verses: [] },
      { chapter: "95", verses: [] },
      { chapter: "96", verses: [] },
      { chapter: "97", verses: [] },
      { chapter: "98", verses: [] },
      { chapter: "99", verses: [] },
      { chapter: "100", verses: [] },
      { chapter: "101", verses: [] },
      { chapter: "102", verses: [] },
      { chapter: "103", verses: [] },
      { chapter: "104", verses: [] },
      { chapter: "105", verses: [] },
      { chapter: "106", verses: [] },
      { chapter: "107", verses: [] },
      { chapter: "108", verses: [] },
      { chapter: "109", verses: [] },
      { chapter: "110", verses: [] },
      { chapter: "111", verses: [] },
      { chapter: "112", verses: [] },
      { chapter: "113", verses: [] },
      { chapter: "114", verses: [] },
      { chapter: "115", verses: [] },
      { chapter: "116", verses: [] },
      { chapter: "117", verses: [] },
      { chapter: "118", verses: [] },
      { chapter: "119", verses: [] },
      { chapter: "120", verses: [] },
      { chapter: "121", verses: [] },
      { chapter: "122", verses: [] },
      { chapter: "123", verses: [] },
      { chapter: "124", verses: [] },
      { chapter: "125", verses: [] },
      { chapter: "126", verses: [] },
      { chapter: "127", verses: [] },
      { chapter: "128", verses: [] },
      { chapter: "129", verses: [] },
      { chapter: "130", verses: [] },
      { chapter: "131", verses: [] },
      { chapter: "132", verses: [] },
      { chapter: "133", verses: [] },
      { chapter: "134", verses: [] },
      { chapter: "135", verses: [] },
      { chapter: "136", verses: [] },
      { chapter: "137", verses: [] },
      { chapter: "138", verses: [] },
      { chapter: "139", verses: [] },
      { chapter: "140", verses: [] },
      { chapter: "141", verses: [] },
      { chapter: "142", verses: [] },
      { chapter: "143", verses: [] },
      { chapter: "144", verses: [] },
      { chapter: "145", verses: [] },
      { chapter: "146", verses: [] },
      { chapter: "147", verses: [] },
      { chapter: "148", verses: [] },
      { chapter: "149", verses: [] },
      { chapter: "150", verses: [] },
    ],
  },
  {
    title: "Proverbs",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
    ],
  },
  {
    title: "Ecclesiastes",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
    ],
  },
  {
    title: "Song of Solomon",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
    ],
  },
  {
    title: "Isaiah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
      { chapter: "41", verses: [] },
      { chapter: "42", verses: [] },
      { chapter: "43", verses: [] },
      { chapter: "44", verses: [] },
      { chapter: "45", verses: [] },
      { chapter: "46", verses: [] },
      { chapter: "47", verses: [] },
      { chapter: "48", verses: [] },
      { chapter: "49", verses: [] },
      { chapter: "50", verses: [] },
      { chapter: "51", verses: [] },
      { chapter: "52", verses: [] },
      { chapter: "53", verses: [] },
      { chapter: "54", verses: [] },
      { chapter: "55", verses: [] },
      { chapter: "56", verses: [] },
      { chapter: "57", verses: [] },
      { chapter: "58", verses: [] },
      { chapter: "59", verses: [] },
      { chapter: "60", verses: [] },
      { chapter: "61", verses: [] },
      { chapter: "62", verses: [] },
      { chapter: "63", verses: [] },
      { chapter: "64", verses: [] },
      { chapter: "65", verses: [] },
      { chapter: "66", verses: [] },
    ],
  },
  {
    title: "Jeremiah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
      { chapter: "41", verses: [] },
      { chapter: "42", verses: [] },
      { chapter: "43", verses: [] },
      { chapter: "44", verses: [] },
      { chapter: "45", verses: [] },
      { chapter: "46", verses: [] },
      { chapter: "47", verses: [] },
      { chapter: "48", verses: [] },
      { chapter: "49", verses: [] },
      { chapter: "50", verses: [] },
      { chapter: "51", verses: [] },
      { chapter: "52", verses: [] },
    ],
  },
  {
    title: "Lamentations",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
    ],
  },
  {
    title: "Ezekiel",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
      { chapter: "15", verses: [] },
      { chapter: "16", verses: [] },
      { chapter: "17", verses: [] },
      { chapter: "18", verses: [] },
      { chapter: "19", verses: [] },
      { chapter: "20", verses: [] },
      { chapter: "21", verses: [] },
      { chapter: "22", verses: [] },
      { chapter: "23", verses: [] },
      { chapter: "24", verses: [] },
      { chapter: "25", verses: [] },
      { chapter: "26", verses: [] },
      { chapter: "27", verses: [] },
      { chapter: "28", verses: [] },
      { chapter: "29", verses: [] },
      { chapter: "30", verses: [] },
      { chapter: "31", verses: [] },
      { chapter: "32", verses: [] },
      { chapter: "33", verses: [] },
      { chapter: "34", verses: [] },
      { chapter: "35", verses: [] },
      { chapter: "36", verses: [] },
      { chapter: "37", verses: [] },
      { chapter: "38", verses: [] },
      { chapter: "39", verses: [] },
      { chapter: "40", verses: [] },
      { chapter: "41", verses: [] },
      { chapter: "42", verses: [] },
      { chapter: "43", verses: [] },
      { chapter: "44", verses: [] },
      { chapter: "45", verses: [] },
      { chapter: "46", verses: [] },
      { chapter: "47", verses: [] },
      { chapter: "48", verses: [] },
    ],
  },
  {
    title: "Daniel",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
    ],
  },
  {
    title: "Hosea",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
    ],
  },
  {
    title: "Joel",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
    ],
  },
  {
    title: "Amos",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
    ],
  },
  {
    title: "Obadiah",
    content: [{ chapter: "1", verses: [] }],
  },
  {
    title: "Jonah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
    ],
  },
  {
    title: "Micah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
    ],
  },
  {
    title: "Nahum",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
    ],
  },
  {
    title: "Habakkuk",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
    ],
  },
  {
    title: "Zehpaniah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
    ],
  },
  {
    title: "Haggai",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
    ],
  },
  {
    title: "Zechariah",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
      { chapter: "5", verses: [] },
      { chapter: "6", verses: [] },
      { chapter: "7", verses: [] },
      { chapter: "8", verses: [] },
      { chapter: "9", verses: [] },
      { chapter: "10", verses: [] },
      { chapter: "11", verses: [] },
      { chapter: "12", verses: [] },
      { chapter: "13", verses: [] },
      { chapter: "14", verses: [] },
    ],
  },
  {
    title: "Malachi",
    content: [
      { chapter: "1", verses: [] },
      { chapter: "2", verses: [] },
      { chapter: "3", verses: [] },
      { chapter: "4", verses: [] },
    ],
  },
  {
    title: "Matthew",
    content: [],
  },
  {
    title: "Mark",
    content: [],
  },
  {
    title: "Luke",
    content: [],
  },
  {
    title: "John",
    content: [],
  },
  {
    title: "Acts",
    content: [],
  },
  {
    title: "Romans",
    content: [],
  },
  {
    title: "1 Corinthians",
    content: [],
  },
  {
    title: "2 Corinthians",
    content: [],
  },
  {
    title: "Galatians",
    content: [],
  },
  {
    title: "Ephesians",
    content: [],
  },
  {
    title: "Philippians",
    content: [],
  },
  {
    title: "Colossians",
    content: [],
  },
  {
    title: "1 Thessalonians",
    content: [],
  },
  {
    title: "2 Thessalonians",
    content: [],
  },
  {
    title: "1 Timothy",
    content: [],
  },
  {
    title: "2 Timothy",
    content: [],
  },
  {
    title: "Titus",
    content: [],
  },
  {
    title: "Philemon",
    content: [],
  },
  {
    title: "Hebrews",
    content: [],
  },
  {
    title: "James",
    content: [],
  },
  {
    title: "1 Peter",
    content: [],
  },
  {
    title: "2 Peter",
    content: [],
  },
  {
    title: "1 John",
    content: [],
  },
  {
    title: "2 John",
    content: [],
  },
  {
    title: "3 John",
    content: [],
  },
  {
    title: "Jude",
    content: [],
  },
  {
    title: "Revelation",
    content: [],
  },
];
